version: 0.2

batch:
  build-list:
    - identifier: connector
      buildspec: dir/buildspec-2.yml
      env:
        compute-type: BUILD_GENERAL1_SMALL

phases:
  install:
    commands:
      - sudo apt-get update && sudo apt-get install vim -y
      - ls
  build:
    commands:
       - vim +PluginInstall +qall
