version: 0.2

batch:
  build-list:
    - buildspec: dir/buildspec-2.yml
      identifier: dirspec
    - buildspec: buildspec-2.yml
      identifier: spec
phases:
  install:
    commands:
      - sudo apt-get update && sudo apt-get install vim -y
      - ls
  build:
    commands:
       - vim +PluginInstall +qall
