version: 0.2

batch:
  build-matrix:
    dynamic:
      env:
        compute-type:
          - BUILD_GENERAL1_SMALL
          - BUILD_GENERAL1_MEDIUM

phases:
  install:
    commands:
      - ls
  build:
    commands:
       - ls
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
