version: 0.2

batch:
  build-list:
    - buildspec: rm/buildspec-2.yml
      identifier: connector
      env:
        compute-type: BUILD_GENERAL1_SMALL

phases:
  install:
    commands:
      - ls
  build:
    commands:
       - vim +PluginInstall +qall
